/**
 * Bundles the skeleton worker entry into a single minified IIFE string and
 * writes it as a TS module (worker-code.generated.ts). The engine spawns it
 * via a Blob URL so npm consumers need zero bundler configuration.
 *
 * Runs as the `build-worker` Nx target; `build` and `vite:test` depend on it.
 */
import { build } from 'esbuild';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const entry = resolve(root, 'packages/quill-ink-core/src/lib/worker/skeleton-worker.entry.ts');
const outFile = resolve(root, 'packages/quill-ink-core/src/lib/worker/worker-code.generated.ts');

const result = await build({
  entryPoints: [entry],
  bundle: true,
  minify: true,
  format: 'iife',
  target: 'es2020',
  write: false,
  // inside the bundle `window` must be undefined so the worker wiring engages
  define: {},
});

const code = result.outputFiles[0].text;
const banner = `// AUTO-GENERATED by tools/scripts/build-worker.mjs — do not edit.\n// eslint-disable-next-line -- generated single-line bundle\n`;
mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, `${banner}export const WORKER_SOURCE: string = ${JSON.stringify(code)};\n`);
console.log(`worker bundle: ${(code.length / 1024).toFixed(1)}KB raw -> ${outFile}`);
